<p style="font-family: Arial; font-size:3em;color:purple; font-style:bold">
An Adapted Intro to numpy:
</p><br>

<i>This is an adapted intro to NumPy based on the following sources: </i><br>
- edX course DSE200x 'Python for Data Science'  (file name is '03_Numpy_Notebook.ipynb')
- https://www.datacamp.com/community/tutorials/python-numpy-tutorial
- http://cs231n.github.io/python-numpy-tutorial


<i>Provided definitions are mostly pulled from Python documentation with some additional edits sparingly throughout.  </i>
<br><br> &nbsp; &nbsp; &nbsp; <i>Natalie Nagata <br> &nbsp; &nbsp; &nbsp; Last updated: Oct. 12, 2017 </i>

<p style="font-family: Arial; font-size:1.25em;color:#2462C0; font-style:bold"><br>
Package for scientific computing with Python
</p>

Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built.  Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.  

The key features of numpy are:

- ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient.  There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).
- Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.
- Vectorization: enables numeric operations on ndarrays.
- Input/Output: simplifies reading and writing of data from/to file.

<b>Additional Recommended Resources:</b><br>
<a href="https://docs.scipy.org/doc/numpy/reference/">Numpy Documentation</a><br>
<i>Python for Data Analysis</i> by Wes McKinney<br>
<i>Python Data science Handbook</i> by Jake VanderPlas


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Getting started with ndarray<br><br></p>

**ndarray** is an n-dimensional array type object that is <u>mutable</u>. ndarray arrays are time and space-efficient.

<br><font size="3"><b>Definition</b></font> 

<p style="font-family: Courier"> array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0) </p>


<font size="3"><b>What is a numpy array?</b></font>
<br>
They're similar to lists in the sense that they hold many values.  But the key difference is that arrays hold data in a <i>structured</i> way.  They're pointers--they contain a memory address, data type, shape, and strides.

- 'data' pointer indicates meory address of first byte in array
- 'dtype' pointer indicates the type of elements contained in the array
- 'shape' indicates shape of array

So arrays contain info about raw data, how to find an element, and how to interpret the element.


In [80]:
import numpy as np
my_array = np.array([1,2,3])

print(my_array.data)
print(my_array.shape)
print(my_array.dtype)
print(my_array.strides)

(3,)
int32
(4,)


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Basic numpy arrays:
</p>

Let's start by making some simple 1-D arrays.

In [81]:
import numpy as np

my_array = np.array([1,2,3])  # Create a rank 1 array

some_zeros = np.zeros([1,5])  # Create a rank 1 array full of zeros

In [82]:
print(my_array)
print(some_zeros)

print(type(my_array))       # The type of an ndarray is: "<class 'numpy.ndarray'>"
print(type(some_zeros))

[1 2 3]
[[ 0.  0.  0.  0.  0.]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


<br><font size="3"><b>Definition</b></font> <p style="font-family: Courier">shape(a)</p>

This returns the shape of an input array as a tuple of ints.  Each element in the tuple gives the lengths of the array's corresponding dimension.

In [83]:
# test the shape of the array we just created, 

print("my_array =         " + str(my_array))
print("my_array shape:    " + str(my_array.shape))       # my_array should have just one dimension (Rank 1)

print("some_zeros =       " + str(some_zeros))
print("some_zeros shape:  " + str(some_zeros.shape))

my_array =         [1 2 3]
my_array shape:    (3,)
some_zeros =       [[ 0.  0.  0.  0.  0.]]
some_zeros shape:  (1, 5)


#### Warning:

<p style="font-family: Arial; font-size:7">
Often people think the shape attribute returns the dimensions of an array. So they would expect the shape of my_array to be (1,3) because there is one row and three columns.  This is incorrect.  The shape attribute returns the length of each <i>dimension</i>.  my_array has only 1 dimension so there is only one value in the shape tuple.  Similarly, some_zeros has 2 dimensions, so the shape tuple has two values.</p>

<p style="font-family: Arial; font-size:7"><i>
"The mistake is thinking of a 1D array as having rows and columns. It does not. It has only one dimension. You can call that single dimension a row, or a column, or whatever else you want. But there is only one of them, which is why the shape has only one member. A line has only a length, a square has a width and a length, a cube has a length, width, and height, and a hypercube has whatever it has (4 or more dimensions.)" </i> </p>

https://www.reddit.com/r/learnpython/comments/4n31ql/need_clarification_in_ndarrayshape/
<br> <br>

In [84]:
# because this is a 1-rank array, we need only 
# one index to accesss each element

print(my_array[0], my_array[1], my_array[2]) 

1 2 3


In [85]:
# ndarrays are mutable!!!! here we change an element of the array

an_array = np.array([3, 33, 333])
an_array[0] =888    

print(an_array)

[888  33 333]


#### Warning:

ndarrays are also <b>typed</b>. If you try to assign an_array[0] to be a string, you get an error

In [86]:
an_array[0] = 'h1'

ValueError: invalid literal for int() with base 10: 'h1'

<br>
<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

How to create a Rank 2 numpy array:</p>

A rank 2 **ndarray** has 2 dimensions.

<br><font size="3"><b>Nested brackets</b></font>

We use nested brackets which have a syntax like this: &nbsp; &nbsp; &nbsp; [ [row] , [row] ].  

2D arrays are great for representing matrices which are often useful in data science.

In [87]:
another = np.array([ [11,12,13], [21,22,23] ])   # Create a rank 2 array

print("another = ")
print(another)

print("Shape is 2 rows, 3 columns: ", another.shape)  # rows x columns                   

print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", another[0, 0], ", ",another[0, 1],", ", another[1, 0])

another = 
[[11 12 13]
 [21 22 23]]
Shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray:  11 ,  12 ,  21


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Other ways to create numpy arrays:
</p>

Here we create a number of different size arrays with different shapes and different pre-filled values.  numpy has a number of built in methods which help us quickly and easily create multidimensional arrays.


<font size="3.5"> <p style="font-family: Courier"><b>zeros</b></p> </font> 
- creates a 2D array of zeros

In [88]:
import numpy as np

ex1 = np.zeros((2,2))      
print(ex1)
print(" ")
print("ex1.shape is... " + str(ex1.shape))       # two rows, two cols

[[ 0.  0.]
 [ 0.  0.]]
 
ex1.shape is... (2, 2)


<br>
<font size="3.5"> <p style="font-family: Courier">
<b> full(shape, fill_value, dtype=None, order='C') </b>
</p> </font> <br>
&emsp; - creates a 2D array of given shape, type, and fill value

In [89]:
# create a 2x2 array filled with 9.0
ex2 = np.full((2,2), 9.0)  

print(ex2)   

[[ 9.  9.]
 [ 9.  9.]]


<br>
<b><font size="3"> <p style="font-family: Courier">
eye(N, M=None, k=0, dtype)
</p> </font> </b> <br>
&emsp; - creates a 2D array of N rows, M cols, k index of diagonal, data type of returned array

In [90]:
# create a 2x2 matrix with the diagonal 1s and the others 0
ex3 = np.eye(2,2)
print(ex3)  

[[ 1.  0.]
 [ 0.  1.]]


<br>
<b><font size="3.5"> <p style="font-family: Courier">
ones(shape, dtype, ...)</p> </font> </b> <br>
&emsp; - returns array of given shape, type, filled with ones

In [91]:
# create an array of ones
ex4 = np.ones((1,2))
print(ex4)
ex4.shape     # one row, two cols

[[ 1.  1.]]


(1, 2)

<br><font size="3"><b>Note:</b></font><br>
&emsp; notice that the above ndarray (ex4) is actually rank 2 (it is a 2x1 array)<br>
&emsp; "rank 2"== length of shape tuple is 2

In [92]:
print(ex4.shape)

# which means we need to use two indexes to access an element
print()
print(ex4[0,1])

(1, 2)

1.0


<br>
<b><font size="3.5"> <p style="font-family: Courier">
random.random(size=None)</p> </font> </b> <br>
&emsp; - returns random floats in the half-open interval &nbsp; &nbsp; [0.0, 1.0)

In [93]:
ex5 = np.random.random((2,2))
print(ex5)    

[[ 0.04370933  0.26910578]
 [ 0.10939895  0.22793933]]


<br><br>
<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Array Indexing
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Slice indexing:
</p>

Similar to the use of slice indexing with lists and strings, we can use slice indexing to pull out sub-regions of ndarrays.

In [94]:
import numpy as np

# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], 
                     [21,22,23,24], 
                     [31,32,33,34]])
print(an_array)
print(an_array.shape)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
(3, 4)


^^^notice the values correspond to its nm (n = row, m = col) position

<br><br><b>IMPORTANT!!!</b> <br>
Use array slicing to get a subarray consisting of the first 2 rows x 2 columns.

In [95]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


<br>
<b>IMPORTANT!!!</b> <br>
When you modify a slice, <b>you actually modify the underlying array.</b> Consider our original values.

In [96]:
print("a_slice: ")
print(a_slice)
a_slice[0, 0] = 1000    # a_slice[0, 0] is the same piece of data as an_array[0, 1]
print("an_array: ")   #inspect the element at 0, 1
print(an_array)

a_slice: 
[[12 13]
 [22 23]]
an_array: 
[[  11 1000   13   14]
 [  21   22   23   24]
 [  31   32   33   34]]


<br> We only alter **a_slice**...but this still changes the original **an_array**...

In [97]:
print("new a_slice: ")
print(a_slice)
print("new an_array: ")   #inspect the element at 0, 1
print(an_array)

new a_slice: 
[[1000   13]
 [  22   23]]
new an_array: 
[[  11 1000   13   14]
 [  21   22   23   24]
 [  31   32   33   34]]


**Slices are references to the SAME underlying data as that of the original array.**

<br>
<b>IMPORTANT!!!</b> <br>
How do you alter a slice without affecting the original array? 
<br>
Answer: you make a copy of the slice. <br><br>
Let's try this again...

In [98]:
an_array = np.array([[11,12,13,14], 
                     [21,22,23,24], 
                     [31,32,33,34]])

a_copy_slice = np.array(an_array[:2, 1:3])
print("a_copy_slice: ")
print(a_copy_slice)
print(" ")

print("an_array (before): ")
print(an_array)
a_copy_slice[0, 0] = 1000
print("an_array (after): ")
print(an_array)

a_copy_slice: 
[[12 13]
 [22 23]]
 
an_array (before): 
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
an_array (after): 
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


<br><br>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold">
Integer indexing, subsetting, & slicing
</p>

We can use integer and slice indexing to create different shaped matrices.

In [99]:
# Create a Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


## Integer indexing

In [100]:
print(an_array[1])

[21 22 23 24]


In [101]:
print(an_array[0])

[11 12 13 14]


<br>
## Subsetting

In [102]:
# Select the element at row 1 column 2
print(an_array[1][2])

23


In [103]:
# Select the element at row 1 column 2
print(an_array[1,2])

23


## Slicing

The basic syntax for slicing is...

<p style="font-family: Courier">
[start : stop : step]
</p>
<br>
For example... Use an index to indicate a row and a colon to indicate a column.

In [104]:
row_rank1 = an_array[1, :]    # Rank 1 view: row 1, all columns

print(row_rank1, row_rank1.shape)  # notice only a single []

[21 22 23 24] (4,)


<br>
<b>IMPORTANT!!!</b> <br>

Look at the shape.  We used a <i>single</i> index to access the row so we are returned a <u>rank 1 array</u>.<br><br>

If I used slices to produce a 1x4 array, it will still be rank 2 (the same rank as an_array).

In [105]:
row_rank2 = an_array[1:2, :]  # Rank 2 view 

print(row_rank2, row_rank2.shape)   # Notice the [[ ]]

[[21 22 23 24]] (1, 4)


<br><br>We can do the same thing for columns of an array:

In [106]:
col_rank1 = an_array[:, 1]         # get first column as rank1
col_rank2 = an_array[:, 1:2]       # get first column as rank2

print(col_rank1, col_rank1.shape)  # 3 element array of Rank 1
print()
print(col_rank2, col_rank2.shape)  # 3x1 array of Rank 2

[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br><br>

Array Indexing for changing elements:
</p>

Sometimes it's useful to use an array of indexes to access or change elements.<br><br> Create a new array:

In [107]:
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])
print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


Create an array representing indices

In [108]:
col_indices = np.array([0, 1, 2, 0])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(4)
print('\nRows indices picked : ', row_indices)


Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3]


Examine the pairings of row_indices and col_indices.  These are the elements we'll change next.

In [109]:
for row,col in zip(row_indices,col_indices):
    print(row, ", ",col)

0 ,  0
1 ,  1
2 ,  2
3 ,  0


Notice it represents the mth row and nth column.  0,0  is the  0th row, 0th col element, etc


Select one element from each row.  Then change one element from each row using the indices selected.  This is all very useful because we can access elements by using arrays as indices and also change elements in an array in the same way.

In [110]:
print('Values in the array at those indices: ',an_array[row_indices, col_indices])
an_array[row_indices, col_indices] += 100000

print('\nChanged Array:')
print(an_array)

Values in the array at those indices:  [11 22 33 41]

Changed Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br><br>
Boolean Indexing

<br></p>
<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Array Indexing for changing elements:
</p>

In [78]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]


array([1, 3, 5])

In [ ]:
# create a 3x2 array
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

In [ ]:
# create a filter which will be boolean values for whether each element meets this condition
filter = (an_array > 15)
filter

Notice that the filter is a same size ndarray as an_array which is filled with True for each element whose corresponding element in an_array which is greater than 15 and False for those elements whose value is less than 15.

In [ ]:
# we can now select just those elements which meet that criteria
print(an_array[filter])

In [ ]:
# For short, we could have just used the approach below without the need for the separate filter array.

an_array[(an_array % 2 == 0)]

What is particularly useful is that we can actually change elements in the array applying a similar logical filter.  Let's add 100 to all the even values.

In [ ]:
an_array[an_array % 2 == 0] +=100
print(an_array)

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Datatypes and Array Operations
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Datatypes:
</p>

In [ ]:
ex1 = np.array([11, 12]) # Python assigns the  data type
print(ex1.dtype)

In [ ]:
ex2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(ex2.dtype)

In [ ]:
ex3 = np.array([11, 21], dtype=np.int64) #You can also tell Python the  data type
print(ex3.dtype)

In [ ]:
# you can use this to force floats into integers (using floor function)
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

In [ ]:
# you can use this to force integers into floats if you anticipate
# the values may change to floats later
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Arithmetic Array Operations:

</p>

In [ ]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

In [ ]:
# add
print(x + y)         # The plus sign works
print()
print(np.add(x, y))  # so does the numpy function "add"

In [ ]:
# subtract
print(x - y)
print()
print(np.subtract(x, y))

In [ ]:
# multiply
print(x * y)
print()
print(np.multiply(x, y))

In [ ]:
# divide
print(x / y)
print()
print(np.divide(x, y))

In [ ]:
# square root
print(np.sqrt(x))

In [ ]:
# exponent (e ** x)
print(np.exp(x))

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Statistical Methods, Sorting, and <br> <br> Set Operations:
<br><br>
</p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Basic Statistical Operations:
</p>

In [ ]:
# setup a random 2 x 4 matrix
arr = 10 * np.random.randn(2,5)
print(arr)

In [ ]:
# compute the mean for all elements
print(arr.mean())

In [ ]:
# compute the means by row
print(arr.mean(axis = 1))

In [ ]:
# compute the means by column
print(arr.mean(axis = 0))

In [ ]:
# sum all the elements
print(arr.sum())

In [ ]:
# compute the medians
print(np.median(arr, axis = 1))

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Sorting:
</p>


In [ ]:
# create a 10 element array of randoms
unsorted = np.random.randn(10)

print(unsorted)

In [ ]:
# create copy and sort
sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)

In [ ]:
# inplace sorting
unsorted.sort() 

print(unsorted)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Finding Unique elements:
</p>

In [ ]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array))

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Set Operations with np.array data type:
</p>

In [ ]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

In [ ]:
print( np.intersect1d(s1, s2) ) 

In [ ]:
print( np.union1d(s1, s2) )

In [ ]:
print( np.setdiff1d(s1, s2) )# elements in s1 that are not in s2

In [ ]:
print( np.in1d(s1, s2) )#which element of s1 is also in s2

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Broadcasting:
<br><br>
</p>

Introduction to broadcasting. <br>
For more details, please see: <br>
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [ ]:
import numpy as np

start = np.zeros((4,3))
print(start)

In [ ]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

In [ ]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

In [ ]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

In [ ]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

In [ ]:
# this will just broadcast in both dimensions
add_scalar = np.array([1])  
print(start+add_scalar)

Example from the slides:

In [ ]:
# create our 3x4 matrix
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

In [ ]:
# create our 4x1 array
arrB = [0,1,0,2]
print(arrB)

In [ ]:
# add the two together using broadcasting
print(arrA + arrB)

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Speedtest: ndarrays vs lists
<br><br>
</p>

First setup paramaters for the speed test. We'll be testing time to sum elements in an ndarray versus a list.

In [ ]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000

In [ ]:
# create the ndarray with values 0,1,2...,size-1
nd_array = arange(size)
print( type(nd_array) )

In [ ]:
# timer expects the operation as a parameter, 
# here we pass nd_array.sum()
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))

In [ ]:
# create the list with values 0,1,2...,size-1
a_list = list(range(size))
print (type(a_list) )

In [ ]:
# timer expects the operation as a parameter, here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list:  %f seconds" % 
      (timer_list.timeit(timeits)/timeits))

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Read or Write to Disk:
<br><br>
</p>

<p style="font-family: Arial; font-size:1.3em;color:#2462C0; font-style:bold"><br>

Binary Format:</p>

In [ ]:
x = np.array([ 23.23, 24.24] )

In [ ]:
np.save('an_array', x)

In [ ]:
np.load('an_array.npy')

<p style="font-family: Arial; font-size:1.3em;color:#2462C0; font-style:bold"><br>

Text Format:</p>

In [ ]:
np.savetxt('array.txt', X=x, delimiter=',')

In [ ]:
!cat array.txt

In [ ]:
np.loadtxt('array.txt', delimiter=',')

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Additional Common ndarray Operations
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Dot Product on Matrices and Inner Product on Vectors:

</p>

In [ ]:
# determine the dot product of two matrices
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))

In [ ]:
# determine the inner product of two vectors
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))

In [ ]:
# dot produce on an array and vector
print(x2d.dot(a1d))
print()
print(np.dot(x2d, a1d))

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Sum:
</p>

In [ ]:
# sum elements in the array
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1))          # add all members

In [ ]:
print(np.sum(ex1, axis=0))  # columnwise sum

In [ ]:
print(np.sum(ex1, axis=1))  # rowwise sum

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Element-wise Functions: </p>

For example, let's compare two arrays values to get the maximum of each.

In [ ]:
# random array
x = np.random.randn(8)
x

In [ ]:
# another random array
y = np.random.randn(8)
y

In [ ]:
# returns element wise maximum between two arrays

np.maximum(x, y)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Reshaping array:
</p>

In [ ]:
# grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr)

In [ ]:
# reshape to be a 4 x 5 matrix
arr.reshape(4,5)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Transpose:

</p>

In [ ]:
# transpose
ex1 = np.array([[11,12],[21,22]])

ex1.T

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Indexing using where():</p>

In [ ]:
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])

filter = np.array([True, False, True, False, True])

In [ ]:
out = np.where(filter, x_1, y_1)
print(out)

In [ ]:
mat = np.random.rand(5,5)
mat

In [ ]:
np.where( mat > 0.5, 1000, -1)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

"any" or "all" conditionals:</p>

In [ ]:
arr_bools = np.array([ True, False, True, True, False ])

In [ ]:
arr_bools.any()

In [ ]:
arr_bools.all()

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Random Number Generation:
</p>

In [ ]:
Y = np.random.normal(size = (1,5))[0]
print(Y)

In [ ]:
Z = np.random.randint(low=2,high=50,size=4)
print(Z)

In [ ]:
np.random.permutation(Z) #return a new ordering of elements in Z

In [ ]:
np.random.uniform(size=4) #uniform distribution

In [ ]:
np.random.normal(size=4) #normal distribution

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Merging data sets:
</p>

In [ ]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

In [ ]:
np.vstack((K,M))

In [ ]:
np.hstack((K,M))

In [ ]:
np.concatenate([K, M], axis = 0)

In [ ]:
np.concatenate([K, M.T], axis = 1)